/** @type {import('tailwindcss').Config} */
const fontStack = [
  "var(--font-mono)",
  "Berkeley Mono",
  "JetBrains Mono",
  "IBM Plex Mono",
  "ui-monospace",
  "SFMono-Regular",
  "Menlo",
  "Monaco",
  "Consolas",
  "Liberation Mono",
  "Courier New",
  "monospace",
];

module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        mono: fontStack,
        sans: fontStack,
      },
      colors: {
        ink: "#201d1d",
        "ink-deep": "#0f0000",
        charcoal: "#302c2c",
        body: "#424245",
        mute: "#646262",
        stone: "#6e6e73",
        ash: "#9a9898",
        canvas: "#fdfcfc",
        "surface-soft": "#f8f7f7",
        "surface-card": "#f1eeee",
        "surface-dark": "#201d1d",
        "surface-dark-elevated": "#302c2c",
        hairline: "rgba(15,0,0,0.12)",
        "hairline-strong": "#646262",
        "on-dark": "#fdfcfc",
        "on-dark-mute": "#9a9898",
        accent: "#007aff",
        "accent-hover": "#0056b3",
        "accent-active": "#004085",
        warning: "#ff9f0a",
        "warning-hover": "#cc7f08",
        danger: "#ff3b30",
        "danger-hover": "#d70015",
        success: "#30d158",
      },
      borderRadius: {
        none: "0px",
        sm: "4px",
        full: "9999px",
      },
      spacing: {
        xxs: "1px",
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        xxl: "32px",
        section: "96px",
      },
      fontSize: {
        "display-xl": ["38px", { lineHeight: "1.5", fontWeight: "700" }],
        "heading-md": ["16px", { lineHeight: "1.5", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-strong": ["16px", { lineHeight: "1.5", fontWeight: "500" }],
        "body-tight": ["16px", { lineHeight: "1", fontWeight: "500" }],
        "button-md": ["16px", { lineHeight: "2", fontWeight: "500" }],
        "caption-md": ["14px", { lineHeight: "2", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
